# Generated by Django 5.0.1 on 2025-07-25 21:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=400, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0, help_text="Depth level in category tree (0 = root)"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (null for top-level categories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["level", "category_code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodas", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pavadinimas",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Last purchase price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "is_internet",
                    models.BooleanField(default=False, help_text="Is e-shop"),
                ),
                (
                    "lead_time",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Lead time in days including transportation and customs clearance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="Is active product"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["kodas"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "sales_quantity",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Quantity sold - returned",
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Quantity in main warehouse",
                        null=True,
                    ),
                ),
                (
                    "potential_sales",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Potential sales based on recent sales trend when stock was adequate",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="app.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products supplied by this supplier",
                        related_name="suppliers",
                        to="app.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kodas__isnull", False), models.Q(("kodas", ""), _negated=True)
                ),
                fields=("kodas",),
                name="unique_kodas_when_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="dailymetrics",
            index=models.Index(
                fields=["product", "date"], name="app_dailyme_product_450ec5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymetrics",
            unique_together={("product", "date")},
        ),
    ]
