# Generated by Django 5.0.1 on 2025-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_daily_purchase",
            field=models.FloatField(
                blank=True,
                help_text="Average daily statistical purchase quantity based on last 365 days",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lead_time",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Lead time in days including transportation and customs clearance",
            ),
        ),
    ]
