# Generated by Django 5.0.1 on 2025-07-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["code"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_kodas_when_not_blank",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="kodas",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pavadinimas",
            new_name="name",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                fields=("code",),
                name="unique_code_when_not_blank",
            ),
        ),
    ]
