# Generated by Django 5.0.1 on 2025-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Supplier model/code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='ERP code', max_length=50, null=True),
        ),
    ]
