# Generated by Django 5.0.1 on 2025-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_product_average_daily_purchase_product_lead_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="suppliers",
        ),
        migrations.AddField(
            model_name="supplier",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products supplied by this supplier",
                related_name="suppliers",
                to="app.product",
            ),
        ),
    ]
