# Generated by Django 5.0.1 on 2025-06-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_product_suppliers_supplier_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "sales_quantity",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Quantity sold minus quantity returned",
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Quantity in main warehouse",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="app.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
    ]
