# Generated by Django 5.0.1 on 2025-07-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_dailymetrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_daily_purchase",
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="is_stockout",
            field=models.BooleanField(default=False, help_text="True if stock was 0"),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="lost_sales",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Lost sales = potential_sales - actual sales_quantity",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailymetrics",
            name="potential_sales",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Potential sales based on recent sales trend when stock was adequate",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="dailymetrics",
            index=models.Index(
                fields=["product", "date"], name="app_dailyme_product_450ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailymetrics",
            index=models.Index(
                fields=["is_stockout"], name="app_dailyme_is_stoc_2989f2_idx"
            ),
        ),
    ]
