# Generated by Django 5.0.1 on 2025-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_moq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=1, help_text='Retailer MOQ if applicable'),
        ),
    ]
