# Generated by Django 5.0.1 on 2025-07-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_product_average_daily_purchase_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dailymetrics",
            name="app_dailyme_is_stoc_2989f2_idx",
        ),
        migrations.RemoveField(
            model_name="dailymetrics",
            name="is_stockout",
        ),
        migrations.AlterField(
            model_name="dailymetrics",
            name="sales_quantity",
            field=models.IntegerField(
                blank=True, default=0, help_text="Quantity sold - returned", null=True
            ),
        ),
    ]
