# Generated by Django 5.0.1 on 2025-07-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_dailymetrics_lost_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_internet',
            field=models.BooleanField(default=False, help_text='Is e-shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Is active product'),
        ),
    ]
